version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: contact-manager-nest
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    tty: true
